### ISSUE TITLE
Instance set by value does not appear in Kaitai Struct output

### ISSUE THREAD

**Issue by jakecrowley** [Mahlet-Inc/hobbits#145]
In the Kaitai Struct plugin, if you have an instance set by a value, it fails to appear in the "Parsed" tab.

for example:
```
instances:
  test1:
    pos: 0
    size: 1
  test2:
    value: 0xff
```

should result in something like this (from kaitai struct visualizer):
![image](https://user-images.githubusercontent.com/8465805/169404788-640b3152-1948-4252-a992-933a5f2a7f1d.png)

however, in Hobbits, it appears like this:
![image](https://user-images.githubusercontent.com/8465805/169404940-adb30574-9051-44da-a547-50d82c95b4a0.png)
