### ISSUE TITLE
Kaitai Struct parsed output table missing 'value' column for some KSY files

### ISSUE THREAD

**Issue by noperator-zz** [Mahlet-Inc/hobbits#155]
Take this ksy for example:
```yaml
meta:
  id: test
seq:
- id: test
  type: test
types:
  test:
    seq:
    - id: t
      type: u1
```
The parsed output table only contains columns 1 and 2, not the third 'value' column.
![image](https://user-images.githubusercontent.com/12838439/203440660-035de5b9-25c0-457f-82b7-250b828119be.png)

Modifying the ksy by adding a field which uses a builtin type at the start of the sequence fixes the issue
```yaml
meta:
  id: test
seq:
- id: test1
  type: u1
- id: test
  type: test
types:
  test:
    seq:
    - id: t
      type: u1
```
![image](https://user-images.githubusercontent.com/12838439/203440585-c24bd771-3839-4b8a-bd90-fb2793c1327c.png)
