### ISSUE TITLE
Relative imports for kaitai structs do not work

### ISSUE THREAD

**Issue by aronwk-aaron** [Mahlet-Inc/hobbits#168]
I'm trying to use relative imports with kaitai, which is a supported [doc](https://doc.kaitai.io/user_guide.html#meta-imports)
however, I get file not found in the tmp directory when I try to do this
![image](https://github.com/Mahlet-Inc/hobbits/assets/26027722/bed4d4ee-ba01-4a53-bfdd-104300d6791c)

Here is the file I am trying to use:
```yaml
meta:
  id: chat
  file-extension: worldchat
  endian: le
  imports:
  - ../header
seq:
  - id: packet_header
    type: header::data
  - id: chat_channel
    type: u1
    enum: chat_channel
  - id: unkonown2
    type: u2
  - id: message
    type: u4_wstr
enums:
  chat_channel:
    ....
```
This is the file structure:
![image](https://github.com/Mahlet-Inc/hobbits/assets/26027722/e9508b5b-1ba9-4a98-8b9c-808344868ab3)

Let me know if there's any other info that I can provide to help resolve this isse
